imports_granularity = "One"
merge_derives = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_small_heuristics = "Max"
reorder_impl_items = true
brace_style = "AlwaysNextLine"
wrap_comments = true
comment_width = 100
fn_single_line = true
format_strings = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
# might remove this or lower num
inline_attribute_width = 100
newline_style = "Unix"
normalize_comments = true
style_edition = "2024"
trailing_comma = "Never"

